spring.application.name=intervi
spring.mongodb.uri=${MONGODB_URI:mongodb+srv://vishal_db_user:vishal_resume@intervi.qleqdqo.mongodb.net/interview-master}
logging.level.org.springframework.data.mongodb=DEBUG

spring.jmx.enabled=false

# Clean terminal output
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr(%-40.40logger{39}){cyan} : %msg%n
logging.level.root=WARN
logging.level.com.intervi=DEBUG
logging.level.org.springframework.web=INFO

GEMINI_API_URL = https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent



GEMINI_API_KEY = AQ.Ab8RN6Jisp8wzMRt9kekBJRbj7T0AsCYdajNQ9f7WZIDmCmA-g



APP_JWT_SECRET = 50435d2e4aa54e4ce0ef72584519add4


APP_JWT_EXPIRE = 86400000

FILE_UPLOAD_DIR = ./uploads