spring.application.name=intervi
spring.mongodb.uri=mongodb+srv://vishal_db_user:vishal_resume@intervi.qleqdqo.mongodb.net/interview-master
logging.level.org.springframework.data.mongodb=DEBUG

spring.jmx.enabled=false

# Clean terminal output
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr(%-40.40logger{39}){cyan} : %msg%n
logging.level.root=WARN
logging.level.com.intervi=DEBUG
logging.level.org.springframework.web=INFO