package com.intervi.resume.services;

import org.springframework.http.*;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import com.intervi.resume.models.InterviewReport;

import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;



@Service
public class AIservices {
    @Value("${gemini.api.key}")
    private String apiKey;

    @Value("${gemini.api.url}")
    private String apiUrl;

    private final RestTemplate restTamplate = new RestTemplate();
    private final ObjectMapper objectMapper = new ObjectMapper();

    public InterviewReport generateReport(String jobDescription, String selfDescription, String resumePath) {
        String prompt = buildPrompt(jobDescription, selfDescription, resumePath);

        String jsonResponse = callGemini(prompt);

        return parseResponse(jsonResponse);

    }

    public String generateResumeData(String selfDescription, String jobDescription, String ResumePath) {
    String prompt = """
            You are a professional resume writer.
            
            Based on the candidate's self description below, extract and structure 
            resume information. Return ONLY valid JSON, no extra text:
            
            Candidate Description:
            """ + selfDescription + """

            Candidate Details:
            """ + ResumePath +"""
            
            Target Job:
            """ + jobDescription + """

            the response should be a JSON object with a single  field "html" which contains the HTML content of the resume which can be coverted into PDF using any library like puppetter
            The resume should be tailored to the target job description, highlighting relevant skills and experience. Use a clean and professional format suitable for ATS systems.HtML content should be complete and ready to be converted into PDF without requiring any additional styling or formatting.
            The resume should include sections like Summary, Skills, Experience, and Education, with content derived from the candidate's self description and resume provided. Focus on making the resume concise, impactful, and relevant to the target job.
            The content of resume not sound like it is generated by AI, it should be natural and human like. Avoid generic phrases and focus on specific achievements and skills that align with the job description.
            you cfan highlight the skills and experience that are most relevant to the job description, and use language that is likely to resonate with hiring managers in that industry. Avoid including irrelevant information or skills that do not add value to the resume. The goal is to create a resume that effectively showcases the candidate's qualifications and increases their chances of getting an interview for the target job.   
            
            """;

    return callGemini(prompt);
}

    private String buildPrompt(String jobDescription, String selfDescription, String resumePath) {

        String resumeInfo = resumePath != null
            ? "Candidate has uploaded a resume: " + resumePath
            : "No resume provided";

        return """
                You are an expert career coach and interview preparation assistant.

                Carefully analyze the candidate's background against the job requirements
                and provide an ACCURATE match score between 0-100 based on:
                    - Skills match (40%)
                    - Experience level match (30%)
                    - Domain knowledge match (30%)
        
                Be strict and realistic. Do NOT always return 75.
                A perfect match = 100, no match at all = 0.

                Analyze the following and generate a detailed interview preparation report.

                Job Description:
                """ + jobDescription + """

                Candidate Background:
                """ + selfDescription + """

                Resume Info:
                """ + resumeInfo + """

                Return ONLY a valid JSON object with exactly this structure, no extra text:
                {
                    "matchScore": <realistic score between 0-100>,
                    "technicalQuestions": [
                        {
                            "question": "question here",
                            "intention": "why interviewer asks this",
                            "answer": "ideal answer here"
                        }
                    ],
                    "behavioralQuestions": [
                        {
                            "question": "question here",
                            "intention": "why interviewer asks this",
                            "answer": "ideal answer here"
                        }
                    ],
                    "skillGaps": [
                        {
                            "skill": "skill name",
                            "severity": "low/medium/high"
                        }
                    ],
                    "preparationPlan": [
                        {
                            "day": 1,
                            "focus": "focus area",
                            "tasks": ["task 1", "task 2"]
                        }
                    ]
                }
                """;
    }
    
    private String callGemini(String prompt) {
        Map<String, Object> parts = new HashMap<>();
        parts.put("text", prompt);

        Map<String, Object> content = new HashMap<>();
        content.put("parts", List.of(parts));

        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("contents", List.of(content));

        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);

        HttpEntity<Map<String, Object>> request = new HttpEntity<>(requestBody, headers);

        String urlWithKey = apiUrl + "?key=" + apiKey;
        System.out.println("Gemini URL: " + urlWithKey);
        ResponseEntity<String> response = restTamplate.postForEntity(urlWithKey, request, String.class);

        return response.getBody();

    }
    
    private InterviewReport parseResponse(String jsonResponse) {
        try {
            JsonNode root = objectMapper.readTree(jsonResponse);
            String text = root
                    .path("candidates")
                    .get(0)
                    .path("content")
                    .path("parts")
                    .get(0)
                    .path("text")
                    .asString();

            text = text.replaceAll("```json", "").replaceAll("```", "").trim();

            return objectMapper.readValue(text, InterviewReport.class);

        } catch (Exception e) {
            throw new RuntimeException("Failed to parse Gemini response: " + e.getMessage());
        }
    }


}
